### ISSUE TITLE
+ in Directory Path can not be handled - likely other special chars?

### ISSUE THREAD

**Issue by crti** [WGSExtract/WGSExtract-Dev#13]
A small issue: 
I have the (latest?) Dev 4.44.2 and it was not starting correctly because I had a "+" in the path (on Windows) like this \WGSExtract\4+Dev\

The error was: 
> \program\settings.py", line 875, in load_settings
>    wgse_message("error", 'InvalidTempDirTitle', True, lang.i18n['errTempDirPath'].replace('{{tempf}}', tempf.oFP))
>TypeError: replace() argument 2 must be str, not None

I was not able to figure this out immediately so maybe it can be fixed in the code

**Comment by RandyHarr** [comment]
A new Dev version was pushed out yesterday.  Rerun your installer to update.  The fix is now in there.

I have been meaning to drop (or fix) that ancient code that is incorrect checking "illegal" characters.  A plus sign should be allowed on all platforms. A quick fix to the allowed characters and that message that bombed on the null pointer in this case has been made in the latest release.

Thank you for reporting this,
